version: '3.8'
services:
  backend:
    build: ./backend
    container_name: fabianatura-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on: []

  auth:
    build: ./auth
    container_name: fabianatura-auth
    ports:
      - "3001:3001"
    env_file:
      - ./auth/.env
    restart: unless-stopped
    depends_on: []